### ISSUE TITLE
textract dependency 

### ISSUE THREAD

**Issue by gravityfargo** [Nyre221/dolphin-quick-view#5]
Hi,
For Archlinux based distros (Manjaro), why are you overriding the system-managed environment to install textract? 
``` pip install textract --break-system-packages ```

The pip warning seems pretty alarming imo
> note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.

[python-textract](https://aur.archlinux.org/packages/python-textract) exists in the AUR

Installing from the AUR worked fine for me.

~``` rm -rf ~/.local/lib/python3.11 ``` removes anything added if the --break-system-packages command was run~

**Comment by RedBearAK** [comment]
@gravityfargo 

Yes, the `pip` warning is alarming, but technically many Linux users have been doing this for years without much of an issue. It was always kind of a bad idea because you could potentially break the Python package that are used by essential parts of the system. But for the most part you're just adding new packages from a similar Python version. It's usually not going to cause a problem, especially if you're not doing `sudo pip` to force things to install at the system level. 

> rm -rf ~/.local/lib/python3.11 removes anything added if the --break-system-packages command was run

No, that would remove literally every Python package you've ever installed in your home library location, if your Python interpreter is version 3.11. That's where everything gets installed by `pip` if you don't use `sudo pip`. Recommending people do that could wipe out completely unrelated packages they may have installed for other reasons. 

What this project needs to do is set up a Python virtual environment location, and then the scripts that launch things will need to activate that virtual environment so they have access to the isolated Python packages and nothing is getting installed either at the system level or in `~/.local/lib/python3.x`. 

I've had to do that with my own project and I'll try to work with the dev if they are interested. It's not too complicated.

**Comment by gravityfargo** [comment]
> No, that would remove literally every Python package you've ever installed in your home library location

Archlinx adopted PEP 668, so every Python package is also an AUR. In my practice, I never use pip outside of virualenv. You are correct, and the rm is awful advice for anyone who doesn't use the AUR, or know what they're doing. In my case, that directory only contained the packages required from the `pip install`  I went ahead and struck that in the og comment.

I don't ever play with other distros anymore, it didn't even cross my mind they do things differently. My bad!

> It was always kind of a bad idea because you could potentially break the Python package that are used by essential parts of the system.

Yeah, in my mind, I don't want to install something with pip to .local, forget about it, and several months later have to figure out why some dependency or something is being wonky.

I'll get acquainted with your code and play with virtualenv this week. Your repo is adding the only functionality I miss from macOS, so I'm invested lol

**Comment by RedBearAK** [comment]
> Archlinx adopted PEP 668, so every Python package is also an AUR.

Oh yeah, I think I heard something about that. How it was pretty weird at first because thousands of new packages just popped up in the AUR and freaked everybody out. Don't think I've heard of other distros doing that just yet. But it seems kind of like a good idea. 

>  I went ahead and struck that in the og comment.

I course of action that I cannot disagree with. 👍🏽  

> I'll get acquainted with your code and play with virtualenv this week. Your repo is adding the only functionality I miss from macOS, so I'm invested lol

Oh, I have nothing to do with this repo, yet. Just excited like you. I can at least tell the dev here how I solved my own issue with needing a `venv`. Maybe you can do something more direct and contribute. 

But this other repo is mine, in case you also miss the keyboard shortcuts from macOS: 

https://github.com/RedBearAK/toshy

**Comment by Nyre221** [comment]
@gravityfargo 
Thanks for the report.
I changed the requirements and removed python-pip.

> What this project needs to do is set up a Python virtual environment location, and then the scripts that launch things will need to activate that virtual environment so they have access to the isolated Python packages and nothing is getting installed either at the system level or in ~/.local/lib/python3.x.

I will do this in the future.
