### ISSUE TITLE
Flathub release

### ISSUE THREAD

**Issue by VictorVow** [Nyre221/dolphin-quick-view#7]
Would love to see this available as a Flatpak to make installation and updates simple.

**Comment by Nyre221** [comment]
I'll think about it.

With flatpak there are two problems that don't make it ideal:
1: I've noticed that typically takes a few seconds longer to open a Qt applications (even lightweight ones)
2: the shortcut must be installed in any case.

These aren't major issues and using flatpak would definitely help a lot with everything else.

**Comment by Nyre221** [comment]
I thought about it and decided that I will try to create a flatpak package (first time) when I have more time.

As I said before, the shortcut and actions in dolphin will have to be installed separately (if I don't find a solution) and therefore it will still be necessary to use an external installer for some components (no more need to install dependencies with apt, dnf, pacman , etc).

For now I have managed to reduce the number of dependencies required by using zipapp: https://github.com/Nyre221/dolphin-quick-view/issues/10

**Comment by Nyre221** [comment]
@Victor239 

This python version requires rewriting some parts to adapt it to flatpak and I don't think it makes sense to do so given the presence of a new C++ version that will soon be installable via flatpak: https://github.com/Nyre221/Kiview

the C++ version is not yet at a stable version but is already on par with the Python one. 
For now it is possible to install it (normal package) on Opensuse Tumbleweed and kde Neon (Plasma 6 only).

You can try the flatpak version in advance by following these instructions:
https://github.com/Nyre221/Kiview/blob/master/extraStuff/BuildFlatpak.txt

The video player isn't the best for now because Qt6+Qml requires a gstreamer extension not available on all distributions and so I'm using Qt WebEngine (for now).
